name: 'Deploy Staging'

on:
  push:
    branches:
      - stage

jobs:
  forge-deploy-staging:
    name: 'Laravel Forge Staging Deploy'
    runs-on: ubuntu-latest

    steps:
      # Trigger Laravel Forge Deploy
      - name: Deploy to Staging
        uses: jbrooksuk/laravel-forge-action@v1.0.2
        with:
          trigger_url: https://forge.laravel.com/servers/871839/sites/2812185/deploy/http?token=iZbV2AiNyMQNtYpK6t8q4L9sXNCnrRZNOcGDAzzc
